"""
Simulator-wide constants.
"""

# Arena
ARENA_SIZE_CM = 200
GRID_SIZE = 20
CELL_SIZE_CM = ARENA_SIZE_CM // GRID_SIZE
START_X=0
START_Y=19

# Display
WINDOW_SIZE_PX = 800
LABEL_SIZE_PX = 40
ARENA_SIZE_PX = WINDOW_SIZE_PX - LABEL_SIZE_PX
CELL_SIZE_PX = ARENA_SIZE_PX // GRID_SIZE

# Robot
ROBOT_SIZE_CM = 30

# Obstacles
OBSTACLE_SIZE_CM = 10